# -*- coding: utf-8 -*-
"""yolov5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pX34AOwSR7Q5r6r6XEUTwA9QJCpMkqgZ
"""

import pandas as pd

# Load the CSV file (adjust the path as needed)
data_path = '/content/full_data_carla.csv'
df = pd.read_csv(data_path)

# Display the first few rows to understand the structure
df.head()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-04-24.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-04-37.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-04-52.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-05-09.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-05-20.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-05-47.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-05-55.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-06-02.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

import torch

# Load the YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5s.pt')

# Perform inference on an image
img_path = '/content/PHOTO-2024-09-18-23-06-11.jpg'  # replace with your image path
results = model(img_path)

# Show results
results.show()  # show the image with bounding boxes
results.save()

data_path = '/content/yolov5s.pt'

data_path = 'yolov5 && python train.py --img 640 --batch 16 --epochs 50 --data /path/to/data.yaml --weights yolov5s.pt --cache'

